services:
  chaveiro:
    build: .
    container_name: chaveiro-system
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file: .env
    environment:
      - PORT=3002
      - TZ=America/Sao_Paulo
    volumes:
      - ./database:/app/database
      - ./public/uploads:/app/public/uploads
      - ./public/downloads:/app/public/downloads
      - ./whatsapp-session:/app/whatsapp-session
      - ./package.json:/app/package.json
      - ./services:/app/services
      - ./routes:/app/routes
      - ./public/js:/app/public/js
      - ./public/css:/app/public/css
      - ./public/app.html:/app/public/app.html
      - ./public/logo.png:/app/public/logo.png
      - ./public/index.html:/app/public/index.html
      - ./views:/app/views
      - ./server.js:/app/server.js
